
services:
  nacos:
    pull_policy: always
    image: nacos/nacos-server:v2.5.1-slim
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=demo
      - NACOS_AUTH_IDENTITY_VALUE=demo
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./nacos-data/:/home/nacos/data
    ports:
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: curl --fail http://127.0.0.1:8848/nacos/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  mysql:
    pull_policy: always
    image: mysql:8.0
    container_name: mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "mysqladmin ping -u root -p\"$${MYSQL_ROOT_PASSWORD}\""
      interval: 2s
      retries: 20
  seata:
    pull_policy: always
    image: apache/seata-server:2.3.0
    container_name: seata
    hostname: "${HOST_IP}"
    depends_on:
      nacos:
        condition: service_healthy
        restart: true
      mysql:
        condition: service_healthy
        restart: true
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      HOST_IP: "${HOST_IP}"
      SEATA_PORT: 8091
      SEATA_IP: "${HOST_IP}"
    volumes:
      - ./seata/application.yml:/seata-server/resources/application.yml
    healthcheck:
      test: curl --fail http://127.0.0.1:7091/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 3