
services:
  nacos:
    image: nacos/nacos-server:v3.1.0-slim
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=demo
      - NACOS_AUTH_IDENTITY_VALUE=demo
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./nacos-data/:/home/nacos/data
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: curl --fail http://127.0.0.1:8848/nacos/actuator || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "mysqladmin ping -u root -p\"$${MYSQL_ROOT_PASSWORD}\""
      interval: 2s
      retries: 20
  seata:
    image: apache/seata-server:2.5.0
    container_name: seata
    hostname: "${HOST_IP}"
    depends_on:
      nacos:
        condition: service_healthy
        restart: true
      mysql:
        condition: service_healthy
        restart: true
    ports:
      - "8091:8091"
    environment:
      HOST_IP: "${HOST_IP}"
      SEATA_PORT: 8091
      SEATA_IP: "${HOST_IP}"
    volumes:
      - ./seata/application.yml:/seata-server/resources/application.yml
    healthcheck:
      test: curl http://127.0.0.1:8091/ || exit 1
      start_period: 10s # wait for service registry
      interval: 5s
      timeout: 5s
      retries: 3
  sn-account-service:
    build: ./sn-account-service
    container_name: sn-account-service
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      seata:
        condition: service_healthy
        restart: true
    ports:
      - 10383:10383
      - 20880:20880
    environment:
      NACOS_URL: "nacos:8848"
      MYSQL_HOST: "mysql:3306"
      HOST_IP: "${HOST_IP}"
      DUBBO_IP_TO_REGISTRY: "${HOST_IP}"
      "spring.cloud.nacos.discovery.ip": "${HOST_IP}"
    healthcheck:
      test: curl --fail http://127.0.0.1:10383/actuator/health/ || exit 1
      start_period: 10s # wait for service registry
      interval: 5s
      timeout: 5s
      retries: 3
  sn-storage-service:
    build: ./sn-storage-service
    container_name: sn-storage-service
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      seata:
        condition: service_healthy
        restart: true
    ports:
      - 10384:10384
      - 20881:20881
    environment:
      NACOS_URL: "nacos:8848"
      MYSQL_HOST: "mysql:3306"
      HOST_IP: "${HOST_IP}"
      DUBBO_IP_TO_REGISTRY: "${HOST_IP}"
      "spring.cloud.nacos.discovery.ip": "${HOST_IP}"
    healthcheck:
      test: curl --fail http://127.0.0.1:10384/actuator/health/ || exit 1
      start_period: 10s # wait for service registry
      interval: 5s
      timeout: 5s
      retries: 3
  sn-order-service:
    build: ./sn-order-service
    container_name: sn-order-service
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      seata:
        condition: service_healthy
        restart: true
    ports:
      - 10385:10385
      - 20882:20882
    environment:
      NACOS_URL: "nacos:8848"
      MYSQL_HOST: "mysql:3306"
      HOST_IP: "${HOST_IP}"
      DUBBO_IP_TO_REGISTRY: "${HOST_IP}"
      "spring.cloud.nacos.discovery.ip": "${HOST_IP}"
    healthcheck:
      test: curl --fail http://127.0.0.1:10385/actuator/health/ || exit 1
      start_period: 10s # wait for service registry
      interval: 5s
      timeout: 5s
      retries: 3
