
services:
  nacos:
    pull_policy: missing
    image: nacos/nacos-server:v2.5.1-slim
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=demo
      - NACOS_AUTH_IDENTITY_VALUE=demo
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./nacos-data/:/home/nacos/data
    ports:
      - "8848:8848"
      - "9848:9848"
  sentinel:
    pull_policy: missing
    image: ghcr.io/opcal/sentinel-dashboard:latest
    container_name: sentinel-dashboard
    ports:
      - 18080:8080
    environment:
      DASHBOARD_SERVER: "localhost:8080"
      USERNAME: demo
      PASSWORD: demo
      SESSION_TIMEOUT: 1440m
      PROJECT_NAME: sentinel-dashboard