
services:
  nacos:
    pull_policy: weekly
    image: nacos/nacos-server:v2.5.1-slim
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=demo
      - NACOS_AUTH_IDENTITY_VALUE=demo
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./nacos-data/:/home/nacos/data
    ports:
      - "8848:8848"
      - "9848:9848"
    healthcheck:
      test: curl --fail http://127.0.0.1:8848/nacos/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  sentinel:
    pull_policy: weekly
    image: ghcr.io/opcal/sentinel-dashboard:latest
    container_name: sentinel-dashboard
    ports:
      - 18080:8080
    environment:
      DASHBOARD_SERVER: "localhost:8080"
      USERNAME: demo
      PASSWORD: demo
      SESSION_TIMEOUT: 1440m
      PROJECT_NAME: sentinel-dashboard
  nd-service-a:
    build: ./nd-service-a
    container_name: nd-service-a
    depends_on:
      nacos:
        condition: service_healthy
        restart: true
    ports:
      - 10380:10380
      - 20880:20880
    environment:
      NACOS_URL: "nacos:8848"
      SENTINEL_URL: "sentinel:8080"
      DUBBO_IP_TO_REGISTRY: "${HOST_IP}"
      "spring.cloud.nacos.discovery.ip": "${HOST_IP}"
    healthcheck:
      test: curl --fail http://127.0.0.1:10380/actuator/health/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  nd-service-b:
    build: ./nd-service-b
    container_name: nd-service-b
    depends_on:
      nacos:
        condition: service_healthy
        restart: true
    ports:
      - 10381:10381
    environment:
      NACOS_URL: "nacos:8848"
      SENTINEL_URL: "sentinel:8080"
      DUBBO_IP_TO_REGISTRY: "${HOST_IP}"
      "spring.cloud.nacos.discovery.ip": "${HOST_IP}"
    healthcheck:
      test: curl --fail http://127.0.0.1:10381/actuator/health/ || exit 1
      interval: 5s
      timeout: 5s
      retries: 3