pipeline {
    agent {
        kubernetes {
            cloud 'kubernetes'
            inheritFrom 'dind-jdk-21-build-nfs-cache'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    parameters {
        choice choices: ['missing', 'always'], name: 'PULL_POLICY'
    }

    stages {
        stage('Validation') {
            steps {
                script {
                    def manual = false
                    def causes = currentBuild.getBuildCauses()
                    for(cause in causes) {
                        if (cause.shortDescription.toString().contains("Started by user")) {
                            manual = true
                        }
                    }
                    def skipCi = sh (script: "git log -1 --pretty=%B | grep '\\[skip ci\\]'", returnStatus: true)
                    echo "${skipCi}"
                    echo "${env.TAG_NAME}"
                    if (manual == false && skipCi == 0 && env.TAG_NAME == null) {
                        echo "Skipping this pipeline by commit message mark!"
                        currentBuild.result = "ABORTED"
                        throw new org.jenkinsci.plugins.workflow.steps.FlowInterruptedException(hudson.model.Result.ABORTED)
                    } else {
                        echo "pipeline build..."
                    }
                }
            }
        }
        stage('Test') {
            steps {
                cache(caches: [
                        arbitraryFileCache(cacheName: '', cacheValidityDecidingFile: '', compressionMethod: 'TARGZ_BEST_SPEED', excludes: '', includes: '**/*', path: '/var/cache/docker')
                ],
                        defaultBranch: 'main',
                        maxCacheSize: 0) {
                    container("dind-jdk-21") {
                        script {
                            sh '''
                                if [ -f /var/cache/docker/docker.tar.gz ]; then
                                    ls -la /var/cache/docker/docker.tar.gz
                                    tar -xzf /var/cache/docker/docker.tar.gz -C /var/lib/docker/
                                    echo "restored docker cache done!"
                                fi
                            '''
                            sh 'start-docker.sh'
                            env.HOST_IP = sh (returnStdout: true, script: "hostname -i").trim()
                            if (params.PULL_POLICY == "always") {
                                sh './ci/script/latest_image.sh'
                            }
                            sh 'printenv HOST_IP'
                            sh "export HOST_IP=${env.HOST_IP};"
                            sh "export PULL_POLICY=${params.PULL_POLICY};"
                            sh "./mvnw -U clean verify"
                            sh 'docker rmi nacos-demos-nd-service-a:latest --force'
                            sh 'docker rmi nacos-demos-nd-service-b:latest --force'
                            sh 'docker rmi seata-nacos-demos-sn-order-service:latest --force'
                            sh 'docker rmi seata-nacos-demos-sn-storage-service:latest --force'
                            sh 'docker rmi seata-nacos-demos-sn-account-service:latest --force'
                            sh 'docker rmi seata-zk-demos-sz-order-service:latest --force'
                            sh 'docker rmi seata-zk-demos-sz-storage-service:latest --force'
                            sh 'docker rmi seata-zk-demos-sz-account-service:latest --force'
                            sh 'docker rmi seata-consul-demos-sc-order-service:latest --force'
                            sh 'docker rmi seata-consul-demos-sc-storage-service:latest --force'
                            sh 'docker rmi seata-consul-demos-sc-account-service:latest --force'
                            sh 'docker container prune -f'
                            sh 'docker image prune -f'
                            sh 'docker volume prune -f'
                            sh 'docker buildx prune -f'
                            sh 'docker builder prune -f'
                            sh 'docker system df'
                            sh 'supervisorctl stop all'
                            sh 'tar -C /var/lib/docker/ -czf /var/cache/docker/docker.tar.gz .'
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        failure {
            script {
                env.AI_EXPLAIN = explainError(
                    maxLines: 10000,
                    logPattern: '(?i)(error|failed|exception)'
                )
            }
            withCredentials([
                string(credentialsId: 'ALERT_MAIL', variable: 'SEND_TO')
            ]) {
                emailext(
                    to: "${SEND_TO}",
                    subject: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - ${currentBuild.currentResult}!",
                    body: "${env.JOB_NAME} - Build # ${env.BUILD_NUMBER} - ${currentBuild.currentResult}. \n\n${env.AI_EXPLAIN}\n\nCheck console output at ${env.BUILD_URL} to view the results."
                )
            }
        }
    }
}