server:
  port: 30384

spring:
  profiles:
    active: dev
  application:
    name: storage-service
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
  cloud:
    consul:
      host: ${CONSUL_HOST:127.0.0.1}
      port: 8500
      discovery:
        register-health-check: false
        prefer-ip-address: true
        ip-address: ${HOST_IP}
  datasource:
    name: accountDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${MYSQL_HOST:127.0.0.1:3306}/test?characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
    username: test
    password: test
    druid:
      max-active: 20
      min-idle: 2
      initial-size: 2
      validation-query: SELECT 1
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      stop:
        command: down
      skip:
        in-tests: false
      file: @basedir@/../docker-compose.yml


seata:
  enabled: true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    disable-global-transaction: false
  registry:
    type: consul
    consul:
      cluster: default
      server-addr: ${spring.cloud.consul.host}:${spring.cloud.consul.port}

dubbo:
  application:
    name: ${spring.application.name}-dubbo
    register-mode: interface
    service-discovery.migration: FORCE_INTERFACE
  scan:
    base-packages: xyz.opcal.demo.cloud.sc.storage.service
  registry:
   address: consul://${spring.cloud.consul.host}:${spring.cloud.consul.port}
  protocols:
    dubbo:
      threadpool: virtual
      port: 20881

